### ISSUE TITLE
Does this configuration work for 4K with High Sierra?

### ISSUE THREAD

**Issue by scottsanett** [gujiangjiang/Hacintosh#2]

**Comment by gujiangjiang** [comment]
I havent test HS yet because XPS is my primary laptop so i dont want to try beta version of OSX.

My old HP laptop has already update to HS beta1234567 and without no problem.

If you want to update to HS you should Drop BGRT or Fix_Header for DSDT to avoid kernel panic.

Good luck.

**Comment by scottsanett** [comment]
Actually I have already installed it on my laptop with Sierra installed in a separate partition. I was writing to ask if anyone has successfully gotten 4K worked out yet. I've been trying to find a fix for this in the past few days with no luck. If you decide to try it out sometime, however, I'd be happy to help/test/whatever. :)
